import { ReactNode } from "react"
import styles from "./BaseLayout.module.css"
import Head from "next/head"
import { Header } from "../Header/Header"
import { Footer } from "../Footer/Footer"

interface BaseLayoutProps {
  children: ReactNode
}

export function BaseLayout(props: BaseLayoutProps) {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles["main"]}>{props.children}</main>
      <Footer />
    </>
  )
}
