type ThisFixesEOFErrorBecauseThisFileIsEmptyWithComments {
	CatsLike: String
}

# Example:

# fragment globalSettings on globalSettings {
#   globalSettingsCollection(limit: 1) {
#     items {
#       ...globalSettingsFields
#     }
#   }
# }