type ThisFixesEOFErrorBecauseThisFileIsEmptyWithComments {
	CatsLike: String
}

# Example:

# query globalSettings {
#   globalSettingsCollection(limit: 1) {
#     items {
#       ...globalSettingsFields
#     }
#   }
# }